"""
================================================================================
LUTRON PROCESSOR CERTIFICATE MANAGER
================================================================================

A unified script that handles all certificate operations for Lutron processors.

FEATURES:
---------
✓ Check status of LAP and LEAP certificates
✓ Discover Lutron processors on the network
✓ Perform LAP certificate handshake
✓ Wait for physical button press on processor
✓ Generate and save LEAP certificates automatically

USAGE:
------
Interactive Menu (Recommended):
    python certificate_manager.py

Check Certificates Only:
    python certificate_manager.py check

Perform Handshake Only:
    python certificate_manager.py handshake

Windows Batch File:
    deployment_scripts\\certificate_manager.bat              # Interactive menu
    deployment_scripts\\certificate_manager.bat check        # Check only
    deployment_scripts\\certificate_manager.bat handshake    # Handshake only
    deployment_scripts\\certificate_manager.bat help         # Show help

CERTIFICATE TYPES:
------------------
1. LAP Certificates (Required for handshake):
   - Obtained from Lutron Developer Portal (https://developer.lutron.com/)
   - Used for initial pairing on port 8083
   - Place in: app/certificates/
   - Files needed:
     * lap_private_key.pem
     * lap_signed_csr.pem
     * lap_lutron_root.crt
     * lap_lutron_intermediate.pem

2. LEAP Certificates (Generated by this script):
   - Created during handshake process
   - Used for ongoing communication on port 8081
   - Automatically saved to: app/certificates/{processor_ip}/
   - Files created (signed certificates from handshake):
     * leap_private_key.pem
     * leap_signed_csr.pem
     * leap_lutron_proc_root.pem
     * leap_lutron_proc_intermediate.pem

HANDSHAKE PROCESS:
------------------
1. Verifies LAP certificates exist
2. Discovers processors via mDNS/Bonjour (5 seconds)
3. Displays list of found processors with details
4. Prompts you to select which processor to pair with
5. Generates LEAP private key and CSR
6. Connects to processor on LAP port 8083
7. Sends Ping to verify connection
8. WAITS FOR PHYSICAL BUTTON PRESS (up to 120 seconds)
   - Button location varies by processor model
   - Usually on front panel or inside device
9. Retrieves processor's root CA certificate
10. Sends CSR to processor for signing
11. Receives signed LEAP certificates
12. Saves all certificates to app/certificates/{processor_ip}/ (IP-based folder)

REQUIREMENTS:
-------------
- Python 3.8+
- Required packages (already in requirements.txt):
  * zeroconf (for processor discovery)
  * cryptography (for key generation)
- LAP certificates from Lutron Developer Portal
- Network access to Lutron processor(s)
- Physical access to press button on processor

TROUBLESHOOTING:
----------------
"Missing required LAP certificates":
  → Download from Lutron Developer Portal
  → Place in app/certificates/ directory

"No Lutron processors found":
  → Ensure processors are powered on
  → Check network connectivity
  → Verify firewall allows mDNS traffic

"Button press not detected":
  → Press and hold button for 2-3 seconds
  → You have 120 seconds after connection
  → Button location varies by processor model

"Connection closed by processor":
  → Verify processor is claimed and configured
  → Check LAP certificates are valid
  → Ensure certificates are from Lutron Developer Portal

SECURITY NOTES:
---------------
- Physical button press required to prevent unauthorized pairing
- LAP certificates can be reused across multiple processors
- LEAP certificates are processor-specific
- Keep all private keys secure - never commit to version control
- Re-run handshake to pair with different/additional processors

CURRENT PROCESSOR INFO:
-----------------------
Working with: Lutron-04e88762.local (192.168.68.201)
System: AthenaProcessor, Serial: 04E88762

For more information:
- Lutron Developer Portal: https://developer.lutron.com/
- LEAP API Documentation: https://developer.lutron.com/api/leap/

================================================================================
"""

import os
import sys
import json
import socket
import ssl
import time
import argparse
from datetime import datetime
from zeroconf import ServiceBrowser, ServiceListener, Zeroconf
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa

# Import project definitions
from app.utils.definitions import (
    LAP_PRIVATE_KEY_FILE,
    LAP_SIGNED_CSR_FILE,
    LAP_LUTRON_ROOT_FILE,
    LAP_LUTRON_INTERMEDIATE_FILE,
    LAP_LUTRON_CHAIN_FILE,
    LEAP_PRIVATE_KEY_FILE,
    LEAP_SIGNED_CSR_FILE,
    LEAP_LUTRON_PROC_ROOT_FILE,
    LEAP_LUTRON_PROC_INTERMEDIATE_FILE,
)

# ============================================================================
# CONSTANTS
# ============================================================================

DEVICE_COMMON_NAME = "Ganakalabs Development"
LAP_PORT = 8083  # Lutron Authentication Protocol port
DISCOVERY_TIMEOUT = 5  # seconds
BUTTON_PRESS_TIMEOUT = 120  # seconds

# ============================================================================
# TERMINAL COLORS
# ============================================================================

class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

# ============================================================================
# OUTPUT HELPERS
# ============================================================================

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*70}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text.center(70)}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*70}{Colors.ENDC}\n")

def print_success(text):
    print(f"{Colors.OKGREEN}[OK] {text}{Colors.ENDC}")

def print_error(text):
    print(f"{Colors.FAIL}[ERROR] {text}{Colors.ENDC}")

def print_warning(text):
    print(f"{Colors.WARNING}[WARNING] {text}{Colors.ENDC}")

def print_info(text):
    print(f"{Colors.OKCYAN}[INFO] {text}{Colors.ENDC}")

# ============================================================================
# CERTIFICATE STATUS CHECKER
# ============================================================================

def check_file(filepath, name):
    """Check if a file exists and get its info"""
    exists = os.path.isfile(filepath)
    
    if exists:
        stat = os.stat(filepath)
        size = stat.st_size
        modified = datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S')
        status = f"{Colors.OKGREEN}[EXISTS]{Colors.ENDC}"
        details = f"({size:,} bytes, modified: {modified})"
    else:
        status = f"{Colors.FAIL}[MISSING]{Colors.ENDC}"
        details = ""
    
    return exists, status, details

def check_certificate_status():
    """Check status of all required certificates"""
    print_header("Lutron Certificate Status Check")
    
    # LAP Certificates
    print(f"{Colors.BOLD}LAP Certificates (Required for handshake):{Colors.ENDC}")
    print(f"{'These must be obtained from Lutron Developer Portal'.center(70)}\n")
    
    lap_certs = [
        (LAP_PRIVATE_KEY_FILE, "LAP Private Key"),
        (LAP_SIGNED_CSR_FILE, "LAP Signed CSR"),
        (LAP_LUTRON_ROOT_FILE, "LAP Lutron Root CA"),
        (LAP_LUTRON_INTERMEDIATE_FILE, "LAP Lutron Intermediate CA"),
    ]
    
    lap_missing = 0
    for filepath, name in lap_certs:
        exists, status, details = check_file(filepath, name)
        print(f"  {status}  {name:<35} {details}")
        if not exists:
            lap_missing += 1
            print(f"           Path: {filepath}")
    
    print()
    
    # LEAP Certificates
    print(f"{Colors.BOLD}LEAP Certificates (Generated by handshake):{Colors.ENDC}")
    print(f"{'These are created by running this script'.center(70)}\n")
    
    leap_certs = [
        (LEAP_PRIVATE_KEY_FILE, "LEAP Private Key"),
        (LEAP_SIGNED_CSR_FILE, "LEAP Signed CSR"),
        (LEAP_LUTRON_PROC_ROOT_FILE, "Processor Root CA"),
        (LEAP_LUTRON_PROC_INTERMEDIATE_FILE, "Processor Intermediate CA"),
    ]
    
    leap_missing = 0
    for filepath, name in leap_certs:
        exists, status, details = check_file(filepath, name)
        print(f"  {status}  {name:<35} {details}")
        if not exists:
            leap_missing += 1
            print(f"           Path: {filepath}")
    
    print()
    
    # Generated Files
    print(f"{Colors.BOLD}Generated Files:{Colors.ENDC}\n")
    gen_files = [(LAP_LUTRON_CHAIN_FILE, "LAP Certificate Chain")]
    for filepath, name in gen_files:
        exists, status, details = check_file(filepath, name)
        print(f"  {status}  {name:<35} {details}")
        if not exists:
            print(f"           Path: {filepath}")
    
    print(f"\n{Colors.BOLD}{'='*70}{Colors.ENDC}\n")
    
    # Summary
    if lap_missing > 0:
        print_warning(f"{lap_missing} LAP certificate(s) missing")
        print(f"\n{Colors.BOLD}Next Steps:{Colors.ENDC}")
        print("  1. Visit Lutron Developer Portal: https://developer.lutron.com/")
        print("  2. Download the LAP certificates")
        print("  3. Place them in: app/certificates/")
        print("  4. Run: python certificate_manager.py handshake")
        return False
    elif leap_missing > 0:
        print_success("All LAP certificates present")
        print_warning(f"{leap_missing} LEAP certificate(s) missing")
        print(f"\n{Colors.BOLD}Next Steps:{Colors.ENDC}")
        print("  1. Run: python certificate_manager.py handshake")
        print("  2. Follow the prompts to pair with a Lutron processor")
        return False
    else:
        print_success("All certificates present!")
        print(f"\n{Colors.BOLD}Your application is ready to connect to Lutron processors{Colors.ENDC}")
        return True

# ============================================================================
# PROCESSOR DISCOVERY
# ============================================================================

class ProcessorDiscovery:
    """Discovers Lutron processors on the network using mDNS/Bonjour"""
    
    def __init__(self):
        self.processors = []
    
    class Listener(ServiceListener):
        def __init__(self, parent):
            self.parent = parent
        
        def add_service(self, zc: Zeroconf, type_: str, name: str) -> None:
            info = zc.get_service_info(type_, name)
            if info:
                processor = {
                    'server': info.server,
                    'ipv4': str(info._ipv4_addresses[0]) if info._ipv4_addresses else None,
                    'system': info.properties.get(b'SYSTYPE', b'').decode("ASCII"),
                    'serial': info.properties.get(b'SERNUM', b'').decode("ASCII"),
                    'mac': info.properties.get(b'MACADDR', b'').decode("ASCII"),
                    'claimed': info.properties.get(b'CLAIM_STATUS', b'').decode("ASCII"),
                    'version': info.properties.get(b'CODEVER', b'').decode("ASCII"),
                }
                if processor['ipv4']:
                    self.parent.processors.append(processor)
        
        def update_service(self, zc: Zeroconf, type_: str, name: str) -> None:
            self.add_service(zc, type_, name)
        
        def remove_service(self, zc: Zeroconf, type_: str, name: str) -> None:
            pass
    
    def discover(self, timeout=DISCOVERY_TIMEOUT):
        """Discover processors on the network"""
        print_info(f"Searching for Lutron processors ({timeout}s)...")
        
        zeroconf = Zeroconf()
        listener = self.Listener(self)
        browser = ServiceBrowser(zeroconf, "_lutron._tcp.local.", listener)
        
        try:
            time.sleep(timeout)
        finally:
            zeroconf.close()
        
        return self.processors

def display_processors(processors):
    """Display discovered processors in a formatted table"""
    if not processors:
        print_error("No Lutron processors found on the network!")
        return False
    
    print(f"\n{Colors.BOLD}Found {len(processors)} Lutron processor(s):{Colors.ENDC}\n")
    print(f"{'#':<4} {'Server':<30} {'IPv4':<16} {'System':<18} {'Serial':<12} {'Status'}")
    print("-" * 100)
    
    for idx, proc in enumerate(processors, 1):
        status = f"{Colors.OKGREEN}{proc['claimed']}{Colors.ENDC}" if proc['claimed'] == 'Claimed' else proc['claimed']
        print(f"{idx:<4} {proc['server']:<30} {proc['ipv4']:<16} {proc['system']:<18} {proc['serial']:<12} {status}")
    
    return True

def select_processor(processors):
    """Prompt user to select a processor"""
    while True:
        try:
            choice = input(f"\n{Colors.BOLD}Select processor number (1-{len(processors)}) or 'q' to quit: {Colors.ENDC}")
            
            if choice.lower() == 'q':
                print_warning("Operation cancelled by user.")
                return None
            
            idx = int(choice) - 1
            if 0 <= idx < len(processors):
                return processors[idx]
            else:
                print_error(f"Invalid selection. Please enter a number between 1 and {len(processors)}.")
        except ValueError:
            print_error("Invalid input. Please enter a number.")

# ============================================================================
# CERTIFICATE OPERATIONS
# ============================================================================

def verify_lap_certificates():
    """Verify LAP certificates exist"""
    print_info("Checking for LAP certificates...")
    
    required_files = [
        ("LAP Private Key", LAP_PRIVATE_KEY_FILE),
        ("LAP Signed CSR", LAP_SIGNED_CSR_FILE),
        ("LAP Lutron Root", LAP_LUTRON_ROOT_FILE),
        ("LAP Lutron Intermediate", LAP_LUTRON_INTERMEDIATE_FILE),
    ]
    
    missing = []
    for name, path in required_files:
        if not os.path.isfile(path):
            missing.append((name, path))
    
    if missing:
        print_error("Missing required LAP certificates:")
        for name, path in missing:
            print(f"  - {name}: {path}")
        print_warning("\nPlease obtain these certificates from Lutron Developer Portal:")
        print_warning("https://developer.lutron.com/")
        return False
    
    print_success("All LAP certificates found")
    return True

def create_lap_chain():
    """Combine LAP root and intermediate certificates into chain file"""
    print_info("Creating LAP certificate chain...")
    
    try:
        with open(LAP_LUTRON_CHAIN_FILE, "w") as dst_file:
            with open(LAP_LUTRON_ROOT_FILE, "r") as src_file:
                dst_file.write(src_file.read())
            with open(LAP_LUTRON_INTERMEDIATE_FILE, "r") as src_file:
                dst_file.write(src_file.read())
        
        print_success("LAP certificate chain created")
        return True
    except Exception as e:
        print_error(f"Failed to create certificate chain: {e}")
        return False

def generate_leap_keys():
    """Generate device-specific private key and CSR for LEAP"""
    print_info("Generating LEAP private key and CSR...")
    
    try:
        cert_subject = x509.Name([
            x509.NameAttribute(NameOID.COMMON_NAME, DEVICE_COMMON_NAME)
        ])
        
        private_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend()
        )
        
        csr = x509.CertificateSigningRequestBuilder().subject_name(
            cert_subject
        ).sign(private_key, hashes.SHA256(), default_backend())
        
        print_success("LEAP key pair and CSR generated")
        return private_key, csr
    
    except Exception as e:
        print_error(f"Failed to generate keys: {e}")
        return None, None

# ============================================================================
# SOCKET HELPERS
# ============================================================================

def send_json(sock, json_msg):
    """Send JSON message to socket"""
    send_msg = (json.dumps(json_msg) + "\r\n").encode("ASCII")
    sock.sendall(send_msg)

def recv_json(sock, timeout=None):
    """Receive JSON message from socket"""
    if timeout:
        sock.settimeout(timeout)
    
    recv_msg = sock.recv(5000)
    
    if timeout:
        sock.settimeout(None)
    
    if len(recv_msg) == 0:
        return None
    
    return json.loads(recv_msg.decode("ASCII"))

# ============================================================================
# LAP HANDSHAKE
# ============================================================================

def perform_lap_handshake(processor, private_key, csr):
    """Perform LAP certificate exchange with processor"""
    
    print_header("LAP Certificate Handshake")
    
    print_info(f"Connecting to {processor['server']} ({processor['ipv4']}) on port {LAP_PORT}...")
    
    try:
        # Setup SSL context with LAP certificates
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        context.verify_mode = ssl.CERT_REQUIRED
        context.load_verify_locations(cafile=LAP_LUTRON_CHAIN_FILE)
        context.load_cert_chain(
            certfile=LAP_SIGNED_CSR_FILE,
            keyfile=LAP_PRIVATE_KEY_FILE
        )
        context.check_hostname = False
        
        # Connect to processor
        sock = socket.create_connection((processor['ipv4'], LAP_PORT), timeout=10)
        ssock = context.wrap_socket(sock)
        sock.close()
        
        print_success(f"Connected to processor on LAP port {LAP_PORT}")
        
        # Step 1: Send Ping
        print_info("Sending Ping request...")
        send_json(ssock, {
            "Header": {
                "RequestType": "Ping",
                "ClientTag": "ping"
            }
        })
        
        recv_msg = recv_json(ssock)
        if not recv_msg or recv_msg["Header"]["StatusCode"] != "204 No Content":
            if recv_msg is None:
                print_error("Processor closed connection. Has the processor been set up with Lutron's tools?")
            else:
                print_error(f"Ping failed: {recv_msg.get('Header', {}).get('StatusCode', 'Unknown error')}")
            return None
        
        print_success("Ping successful")
        
        # Step 2: Wait for physical button press
        print_header("Physical Access Verification Required")
        print_warning(f"Please press the button on processor {processor['serial']}")
        print_info("Button location varies by device (usually on front panel or inside)")
        print_info(f"Waiting for button press (timeout: {BUTTON_PRESS_TIMEOUT}s)...")
        print(f"{Colors.BOLD}Press the button NOW...{Colors.ENDC}")
        
        recv_msg = recv_json(ssock, timeout=BUTTON_PRESS_TIMEOUT)
        if not recv_msg or recv_msg["Header"]["StatusCode"] != "200 OK":
            print_error("Button press not detected or timeout occurred")
            return None
        
        print_success("Button press detected! Physical access verified")
        
        # Step 3: Retrieve processor's root CA certificate
        print_info("Retrieving processor's root CA certificate...")
        send_json(ssock, {
            "Header": {
                "RequestType": "Read",
                "Url": "/certificate/root",
                "ClientTag": "read-root",
            },
        })
        
        root_resp = recv_json(ssock)
        if not root_resp or root_resp["Header"]["StatusCode"] != "200 OK":
            print_error("Failed to retrieve processor root certificate")
            return None
        
        proc_root_cert = root_resp["Body"]["Certificate"]["Certificate"]
        print_success("Processor root certificate received")
        
        # Step 4: Send CSR for signing
        print_info("Sending CSR to processor for signing...")
        send_json(ssock, {
            "Header": {
                "RequestType": "Execute",
                "Url": "/pair",
                "ClientTag": "get-cert",
            },
            "Body": {
                "CommandType": "CSR",
                "Parameters": {
                    "CSR": csr.public_bytes(serialization.Encoding.PEM).decode('ASCII'),
                    "DisplayName": DEVICE_COMMON_NAME,
                    "DeviceUID": "000000000000"
                },
            },
        })
        
        recv_msg = recv_json(ssock)
        if not recv_msg or recv_msg["Header"]["StatusCode"] != "200 OK":
            print_error("CSR signing failed")
            return None
        
        print_success("CSR signed successfully by processor")
        
        # Extract certificates from response
        signed_csr = recv_msg["Body"]["SigningResult"]["Certificate"]
        proc_intermediate_cert = recv_msg["Body"]["SigningResult"]["RootCertificate"]
        private_key_pem = private_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption()
        ).decode('ASCII')
        
        ssock.close()
        
        return {
            'private_key': private_key_pem,
            'signed_csr': signed_csr,
            'proc_root': proc_root_cert,
            'proc_intermediate': proc_intermediate_cert,
        }
    
    except socket.timeout:
        print_error(f"Connection timeout - button not pressed within {BUTTON_PRESS_TIMEOUT} seconds")
        return None
    except Exception as e:
        print_error(f"LAP handshake failed: {e}")
        import traceback
        traceback.print_exc()
        return None

def save_leap_certificates(certs, processor_ipv4):
    """Save LEAP certificates to processor-specific directory"""
    print_header("Saving LEAP Certificates")
    
    # Create processor-specific certificate directory
    cert_dir = f"app/certificates/{processor_ipv4}"
    os.makedirs(cert_dir, exist_ok=True)
    print_info(f"Saving certificates to: {cert_dir}")
    
    # Define expected LEAP certificate files
    leap_cert_files = [
        ("leap_private_key.pem", certs['private_key'], "LEAP Private Key"),
        ("leap_signed_csr.pem", certs['signed_csr'], "LEAP Signed CSR"),
        ("leap_lutron_proc_root.pem", certs['proc_root'], "Processor Root Certificate"),
        ("leap_lutron_proc_intermediate.pem", certs['proc_intermediate'], "Processor Intermediate Certificate"),
    ]
    
    # Check if folder already exists with certificates
    folder_exists = os.path.exists(cert_dir) and os.path.isdir(cert_dir)
    if folder_exists:
        # List all files in the directory
        existing_files = []
        if os.path.exists(cert_dir):
            for item in os.listdir(cert_dir):
                item_path = os.path.join(cert_dir, item)
                if os.path.isfile(item_path):
                    existing_files.append(item)
        
        if existing_files:
            # Check for old LEAP certificates
            old_leap_files = [f for f in existing_files if f.startswith("leap_")]
            # Check for obsolete LAP certificates (shouldn't be in IP folder)
            obsolete_lap_files = [f for f in existing_files if f.startswith("lap_")]
            
            if old_leap_files or obsolete_lap_files:
                print_warning(f"Found existing files in {cert_dir}:")
                if old_leap_files:
                    for f in old_leap_files:
                        print_warning(f"  - {f} (will be overwritten)")
                if obsolete_lap_files:
                    for f in obsolete_lap_files:
                        print_warning(f"  - {f} (obsolete, will be removed)")
                    # Remove obsolete LAP files
                    for filename in obsolete_lap_files:
                        try:
                            filepath = os.path.join(cert_dir, filename)
                            os.remove(filepath)
                            print_info(f"Removed obsolete file: {filename}")
                        except Exception as e:
                            print_warning(f"Could not remove {filename}: {e}")
    
    # Save LEAP certificates (overwrites existing)
    for filename, content, name in leap_cert_files:
        try:
            filepath = os.path.join(cert_dir, filename)
            with open(filepath, "w") as f:
                f.write(content)
            print_success(f"{name} saved to {filepath}")
        except Exception as e:
            print_error(f"Failed to save {name}: {e}")
            return False
    
    return True

# ============================================================================
# MAIN WORKFLOWS
# ============================================================================

def run_handshake():
    """Execute the complete certificate handshake workflow"""
    print_header("Lutron Processor Certificate Handshake")
    print(f"{Colors.BOLD}This will pair your application with a Lutron processor{Colors.ENDC}")
    print(f"{Colors.BOLD}using the LAP (Lutron Authentication Protocol){Colors.ENDC}\n")
    
    # Step 1: Check LAP certificates
    if not verify_lap_certificates():
        return False
    
    # Step 2: Create certificate chain
    if not create_lap_chain():
        return False
    
    # Step 3: Discover processors
    discovery = ProcessorDiscovery()
    processors = discovery.discover()
    
    if not display_processors(processors):
        return False
    
    # Step 4: Select processor
    processor = select_processor(processors)
    if not processor:
        return False
    
    print(f"\n{Colors.OKGREEN}Selected: {processor['server']} ({processor['ipv4']}){Colors.ENDC}")
    print(f"System: {processor['system']}, Serial: {processor['serial']}, MAC: {processor['mac']}\n")
    
    # Step 5: Generate LEAP keys
    private_key, csr = generate_leap_keys()
    if not private_key or not csr:
        return False
    
    # Step 6: Perform LAP handshake
    certs = perform_lap_handshake(processor, private_key, csr)
    if not certs:
        print_error("\nCertificate handshake failed!")
        return False
    
    # Step 7: Save certificates
    if not save_leap_certificates(certs, processor['ipv4']):
        print_error("\nFailed to save certificates!")
        return False
    
    # Success!
    print_header("Certificate Handshake Complete!")
    print_success("Your application is now paired with the Lutron processor")
    print_info("You can now connect to the processor using LEAP on port 8081")
    print_info(f"The certificates have been saved to app/certificates/{processor['ipv4']}/")
    print(f"\n{Colors.BOLD}Next steps:{Colors.ENDC}")
    print("  1. Restart your application to use the new certificates")
    print("  2. Your app will automatically connect to the processor")
    print()
    
    return True

def show_menu():
    """Display interactive menu"""
    print_header("Lutron Certificate Manager")
    print(f"{Colors.BOLD}Select an operation:{Colors.ENDC}\n")
    print("  1. Check certificate status")
    print("  2. Perform certificate handshake")
    print("  3. Exit")
    print()
    
    while True:
        try:
            choice = input(f"{Colors.BOLD}Enter your choice (1-3): {Colors.ENDC}")
            
            if choice == '1':
                print()
                check_certificate_status()
                print()
                return
            elif choice == '2':
                print()
                run_handshake()
                return
            elif choice == '3':
                print_info("Goodbye!")
                return
            else:
                print_error("Invalid choice. Please enter 1, 2, or 3.")
        except (KeyboardInterrupt, EOFError):
            print(f"\n{Colors.WARNING}Operation cancelled by user.{Colors.ENDC}")
            return

# ============================================================================
# MAIN ENTRY POINT
# ============================================================================

def main():
    """Main execution flow"""
    parser = argparse.ArgumentParser(
        description="Lutron Processor Certificate Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python certificate_manager.py              # Interactive menu
  python certificate_manager.py check        # Check certificate status
  python certificate_manager.py handshake    # Perform handshake
        """
    )
    
    parser.add_argument(
        'action',
        nargs='?',
        choices=['check', 'handshake'],
        help='Action to perform (if not specified, shows interactive menu)'
    )
    
    args = parser.parse_args()
    
    try:
        if args.action == 'check':
            check_certificate_status()
        elif args.action == 'handshake':
            run_handshake()
        else:
            show_menu()
    
    except KeyboardInterrupt:
        print(f"\n\n{Colors.WARNING}Operation cancelled by user.{Colors.ENDC}")
        sys.exit(0)
    except Exception as e:
        print_error(f"\nUnexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()

