from app.utils.paths import get_base_dir, get_certificates_dir  # LUTRON_EXE_CERTIFICATES_ROOT
import os

BACKEND_ROOT = get_base_dir()
CERTIFICATES_ROOT = get_certificates_dir()

# LEAP_PRIVATE_KEY_FILE = r"C:\Users\HARSHITHA\Desktop\Lutron Backend\Lutron_backend_app\app\certificates\leap_private_key.pem"
# LEAP_SIGNED_CSR_FILE = r"C:\Users\HARSHITHA\Desktop\Lutron Backend\Lutron_backend_app\app\certificates\leap_signed_csr.pem"
# LAP_LUTRON_ROOT_FILE = r"C:\Users\HARSHITHA\Desktop\Lutron Backend\Lutron_backend_app\app\certificates\lap_lutron_root.crt"

# LAP Certificates (obtained from Lutron Developer Portal - required for handshake)
LAP_PRIVATE_KEY_FILE = os.path.join(CERTIFICATES_ROOT, "lap_private_key.pem")
LAP_SIGNED_CSR_FILE = os.path.join(CERTIFICATES_ROOT, "lap_signed_csr.pem")
LAP_LUTRON_ROOT_FILE = os.path.join(CERTIFICATES_ROOT, "lap_lutron_root.crt")
LAP_LUTRON_INTERMEDIATE_FILE = os.path.join(CERTIFICATES_ROOT, "lap_lutron_intermediate.pem")
LAP_LUTRON_CHAIN_FILE = os.path.join(CERTIFICATES_ROOT, "lap_lutron_chain.pem")

# LEAP Certificates (generated by certificate_handshake.py - used for processor communication)
LEAP_PRIVATE_KEY_FILE = os.path.join(CERTIFICATES_ROOT, "leap_private_key.pem")
LEAP_SIGNED_CSR_FILE = os.path.join(CERTIFICATES_ROOT, "leap_signed_csr.pem")
LEAP_LUTRON_PROC_ROOT_FILE = os.path.join(CERTIFICATES_ROOT, "leap_lutron_proc_root.pem")
LEAP_LUTRON_PROC_INTERMEDIATE_FILE = os.path.join(CERTIFICATES_ROOT, "leap_lutron_proc_intermediate.pem")


def get_proc_hostname(system: str, mac: str) -> str:
    return f"{system.lower()}-{mac.lower().replace(':', '')}-server"


def get_processor_cert_paths(processor_ipv4: str = None) -> dict:
    """
    Get certificate file paths for specific processor or raise error.
    
    Args:
        processor_ipv4: IPv4 address of processor (e.g., "192.168.1.100")
                       Required - cannot be None
    
    Returns:
        dict: Certificate file paths for the processor
        
    Raises:
        Exception: If processor_ipv4 is not provided
    """
    if processor_ipv4:
        cert_dir = os.path.join(CERTIFICATES_ROOT, processor_ipv4)
        return {
            'lap_root': f"{cert_dir}/lap_lutron_root.crt",
            'leap_private_key': f"{cert_dir}/leap_private_key.pem",
            'leap_signed_csr': f"{cert_dir}/leap_signed_csr.pem",
        }
    else:
        raise Exception("certificate invalid")